### PR TITLE
Fixed a bug where load session crashes the session

### PR DESCRIPTION
**Pull request by Vuwij**
I fixed Load Session

### CODE REVIEW

**Comment by sailamshama** [comment]
Added fix

**Comment by Vuwij** [comment]
Ok changed it to that way

**Comment by abidihaider** [comment]
Hi Vuwij, 

Do you know if there was discussion from the lab admins to update the code that is on the lab computers and/or what they provide the students, or should we try to follow this up?


Thanks

**Comment by Vuwij** [comment]
Yes they are going to update it. Thanks

Regards,
Jason Wang, Computer Eng. Student
Tel: 647-879-4660 | Skype: Jaw.vuwij

On Oct 3, 2017, at 12:43 PM, abidihaider <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vuwij,

Do you know if there was discussion from the lab admins to update the code that is on the lab computers and/or what they provide the students, or should we try to follow this up?

Thanks

**Comment by sailamshama** [comment]
Hi Abidi,

Apologies if that's not the name you're called by.

I just finished working on the HEP experiment and mentioned the software
update to Prof. Netterfield.  I'll talk to you him about updating the
software in the labs.

Thanks,
Saila

**Pull request merged**
